#ifndef MSYSTICK_CFG_H_
#define MSYSTICK_CFG_H_

/*
    MSYSTICK_CLOCK_SOURCE_AHB_BY_8
    MSYSTICK_CLOCK_SOURCE_AHB
*/
#define MSYSTIC_CLOCK_SOURCE MSYSTICK_CLOCK_SOURCE_AHB

/*
    MSYSTICK_DISABLE_EXCEPTION_REQUEST
    MSYSTICK_ENABLE_EXCEPTION_REQUEST
*/
#define MSYSTICK_TICKINT MSYSTICK_ENABLE_EXCEPTION_REQUEST

#endif